// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkAEYxrO3wIMEQtB5a4t9AWAK7-DTCoY0',
    appId: '1:986364973775:web:18161f32cfd98ed3035dba',
    messagingSenderId: '986364973775',
    projectId: 'chatapp-d8629',
    authDomain: 'chatapp-d8629.firebaseapp.com',
    databaseURL: 'https://chatapp-d8629-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'chatapp-d8629.appspot.com',
    measurementId: 'G-E8ZELVMWVC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0n95JO_b_uaFt1aszI41B2AX4wgYwnJs',
    appId: '1:986364973775:android:a73960ac6ab9c2ef035dba',
    messagingSenderId: '986364973775',
    projectId: 'chatapp-d8629',
    databaseURL: 'https://chatapp-d8629-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'chatapp-d8629.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChw1vLeT3CIhfcrrZQYL3U2gWVwZ9jZz8',
    appId: '1:986364973775:ios:74f6803e41204496035dba',
    messagingSenderId: '986364973775',
    projectId: 'chatapp-d8629',
    databaseURL: 'https://chatapp-d8629-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'chatapp-d8629.appspot.com',
    iosClientId: '986364973775-rrtkfriurp2ggqmu8vd2c72gidtdh2jg.apps.googleusercontent.com',
    iosBundleId: 'com.example.minka',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChw1vLeT3CIhfcrrZQYL3U2gWVwZ9jZz8',
    appId: '1:986364973775:ios:74f6803e41204496035dba',
    messagingSenderId: '986364973775',
    projectId: 'chatapp-d8629',
    databaseURL: 'https://chatapp-d8629-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'chatapp-d8629.appspot.com',
    iosClientId: '986364973775-rrtkfriurp2ggqmu8vd2c72gidtdh2jg.apps.googleusercontent.com',
    iosBundleId: 'com.example.minka',
  );
}
